---
development:
  cloud_name: aquakiss
  api_key: '764662733984751'
  api_secret: nO016tmxavivX_uIaZkHHLblR8k
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: aquakiss
  api_key: '764662733984751'
  api_secret: nO016tmxavivX_uIaZkHHLblR8k
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: aquakiss
  api_key: '764662733984751'
  api_secret: nO016tmxavivX_uIaZkHHLblR8k
  enhance_image_tag: true
  static_image_support: false
